server:
  port: 8181

spring:
  jpa:
    show-sql: true
    generate-ddl: true
  hibernate:
    ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgresDB?currentSchema=public
    username: sa
    password: password
    driverClassName: org.postgresql.Driver
  sql:
    init:
      mode: always
      platform: postgres
      schema-locations: classpath:init-schema.sql

