--DROP SCHEMA IF EXISTS "credit" CASCADE;
--
--CREATE SCHEMA "credit";
--
--CREATE TABLE "credit".customer
--(
--    id uuid NOT NULL,
--    name varchar(255),
--    surname varchar(255),
--    credit_limit numeric(38,2),
--    used_credit_limit numeric(38,2),
--    primary key (id)
--);